# Feature Engineering

---

1. Import packages
2. Load data
3. Feature engineering

---

## 1. Import packages

In [123]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

---
## 2. Load data

In [124]:
df = pd.read_csv('./clean_data_after_eda.csv')
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

In [125]:
df

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
14602,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,...,0.000009,2.225451e-06,1.802667e-08,0.014939,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1
14603,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1
14604,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
14605,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0

---

## 3. Feature engineering

### Difference between off-peak prices in December and preceding January

Below is the code created by your colleague to calculate the feature described above. Use this code to re-create this feature and then think about ways to build on this feature to create features with a higher predictive power.

In [126]:
price_df = pd.read_csv('price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [127]:
df

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
14602,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,...,0.000009,2.225451e-06,1.802667e-08,0.014939,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1
14603,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1
14604,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
14605,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0

In [128]:
# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get january and december prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001

Now it is time to get creative and to conduct some of your own feature engineering! Have fun with it, explore different ideas and try to create as many as you can!

In [129]:
diff

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001
...,...,...,...
16091,ffef185810e44254c3a4c6395e6b4d8a,-0.050232,-0.335085
16092,fffac626da707b1b5ab11e8431a4d0a2,-0.003778,0.177779
16093,fffc0cacd305dd51f316424bbb08d1bd,-0.001760,0.164916
16094,fffe4f5646aa39c7f97f95ae2679ce64,-0.009391,0.162916
16095,ffff7fa066f1fb305ae285bb03bf325a,-0.009528,0.162916

In [130]:
# Check the number of unique values in all columns
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

# Remove redundant columns with too little unique values
df.drop(columns=['forecast_discount_energy', 'forecast_cons_12m', 'forecast_cons_year', 'forecast_price_pow_off_peak', 
                 'forecast_meter_rent_12m', 'forecast_price_energy_off_peak', 'forecast_price_energy_peak'], inplace=True)

id: 14606 unique values
channel_sales: 8 unique values
cons_12m: 11065 unique values
cons_gas_12m: 2112 unique values
cons_last_month: 4751 unique values
date_activ: 1796 unique values
date_end: 368 unique values
date_modif_prod: 2129 unique values
date_renewal: 386 unique values
forecast_cons_12m: 13993 unique values
forecast_cons_year: 4218 unique values
forecast_discount_energy: 12 unique values
forecast_meter_rent_12m: 3528 unique values
forecast_price_energy_off_peak: 516 unique values
forecast_price_energy_peak: 329 unique values
forecast_price_pow_off_peak: 41 unique values
has_gas: 2 unique values
imp_cons: 7752 unique values
margin_gross_pow_ele: 2391 unique values
margin_net_pow_ele: 2391 unique values
nb_prod_act: 10 unique values
net_margin: 11965 unique values
num_years_antig: 13 unique values
origin_up: 6 unique values
pow_max: 698 unique values
var_year_price_off_peak_var: 4674 unique values
var_year_price_peak_var: 2696 unique values
var_year_price_mid_peak_var: 1893 unique values
var_year_price_off_peak_fix: 885 unique values
var_year_price_peak_fix: 380 unique values
var_year_price_mid_peak_fix: 374 unique values
var_year_price_off_peak: 5766 unique values
var_year_price_peak: 2936 unique values
var_year_price_mid_peak: 2145 unique values
var_6m_price_off_peak_var: 2401 unique values
var_6m_price_peak_var: 1412 unique values
var_6m_price_mid_peak_var: 873 unique values
var_6m_price_off_peak_fix: 256 unique values
var_6m_price_peak_fix: 110 unique values
var_6m_price_mid_peak_fix: 106 unique values
var_6m_price_off_peak: 2572 unique values
var_6m_price_peak: 1497 unique values
var_6m_price_mid_peak: 956 unique values
churn: 2 unique values

In [131]:
# Check the number of unique values in all columns
for col in price_df.columns:
    print(f"{col}: {price_df[col].nunique()} unique values")

# Remove redundant columns values
price_df.drop(columns=['price_mid_peak_var', 'price_mid_peak_fix'], inplace=True)

id: 16096 unique values
price_date: 12 unique values
price_off_peak_var: 1853 unique values
price_peak_var: 1189 unique values
price_mid_peak_var: 711 unique values
price_off_peak_fix: 66 unique values
price_peak_fix: 31 unique values
price_mid_peak_fix: 28 unique values

In [132]:
price_df

,id,price_date,price_off_peak_var,price_peak_var,price_off_peak_fix,price_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.000000,44.266931,0.00000
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.000000,44.266931,0.00000
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.000000,44.266931,0.00000
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.000000,44.266931,0.00000
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.000000,44.266931,0.00000
...,...,...,...,...,...,...
192997,16f51cdc2baa19af0b940ee1b3dd17d5,2015-08-01,0.119916,0.102232,40.728885,24.43733
192998,16f51cdc2baa19af0b940ee1b3dd17d5,2015-09-01,0.119916,0.102232,40.728885,24.43733
192999,16f51cdc2baa19af0b940ee1b3dd17d5,2015-10-01,0.119916,0.102232,40.728885,24.43733
193000,16f51cdc2baa19af0b940ee1b3dd17d5,2015-11-01,0.119916,0.102232,40.728885,24.43733
193001,16f51cdc2baa19af0b940ee1b3dd17d5,2015-12-01,0.119916,0.102232,40.728885,24.43733

### Temporal Trends

In [133]:
# Time-related features

# Capture the lenght of the contract in months, # longer the tenure, the less likely the churn
df['tenure_months'] = (df['date_end'] - df['date_activ']).dt.days / 30

In [134]:
# Drop the date columns that are not needed anymore
df.drop(columns=['date_activ', 'date_end', 'date_modif_prod', 'date_renewal'], inplace=True)

df

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,...,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn,tenure_months
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,t,0.00,25.44,25.44,2,...,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1,36.533333
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,f,0.00,16.38,16.38,1,...,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,85.533333
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,f,0.00,28.60,28.60,1,...,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,73.066667
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,f,0.00,30.22,30.22,1,...,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,73.066667
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,f,52.32,44.91,44.91,1,...,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0,74.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,t,0.00,27.88,27.88,2,...,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,48.166667
14602,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,f,15.94,0.00,0.00,1,...,2.225451e-06,1.802667e-08,0.014939,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1,48.700000
14603,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,f,18.05,39.84,39.84,1,...,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1,48.666667
14604,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,f,0.00,13.08,13.08,1,...,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,48.700000
14605,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,f,0.00,11.84,11.84,1,...,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,85.200000

### Consumption-Based Ratios & Trends

In [135]:
# Get some behavioral features to capture the consumption patterns

# Remove conterintuitive values
df = df[~((df['cons_12m'] <= 0) & (df['cons_last_month'] >= 0))]

# Tells if last month consumption is typical or not, closer to 1 means more typical
df['consistency_ratio'] = df['cons_last_month'] / (df['cons_12m'] / 12)

df

/var/folders/wh/t3j80ytd48d5dgkgctlzn6xh0000gn/T/ipykernel_31462/2043563419.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['consistency_ratio'] = df['cons_last_month'] / (df['cons_12m'] / 12)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,...,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn,tenure_months,consistency_ratio
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,f,0.00,16.38,16.38,1,...,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,85.533333,0.000000
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,f,0.00,28.60,28.60,1,...,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,73.066667,0.000000
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,f,0.00,30.22,30.22,1,...,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,73.066667,0.000000
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,f,52.32,44.91,44.91,1,...,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0,74.833333,1.426441
5,1aa498825382410b098937d65c4ec26d,usilxuppasemubllopkaafesmlibmsdf,8302,0,1998,f,181.21,33.12,33.12,1,...,0.000000e+00,0.000000,0.000000,0.000000,0.000010,4.240524e-06,0.000000e+00,1,60.900000,2.887979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,t,0.00,27.88,27.88,2,...,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,48.166667,0.000000
14602,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,f,15.94,0.00,0.00,1,...,1.802667e-08,0.014939,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1,48.700000,0.300706
14603,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,f,18.05,39.84,39.84,1,...,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1,48.666667,1.164859
14604,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,f,0.00,13.08,13.08,1,...,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,48.700000,0.000000
14605,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,f,0.00,11.84,11.84,1,...,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,85.200000,0.000000

### Final Preprocessing

In [136]:
# Merge the off-peak price difference with the main dataframe
df = pd.merge(df, diff, on='id', how='left')
df

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,...,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn,tenure_months,consistency_ratio,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,f,0.00,16.38,16.38,1,...,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,85.533333,0.000000,-0.003767,0.177779
1,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,f,0.00,28.60,28.60,1,...,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,73.066667,0.000000,-0.004670,0.177779
2,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,f,0.00,30.22,30.22,1,...,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,73.066667,0.000000,-0.004547,0.177779
3,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,f,52.32,44.91,44.91,1,...,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0,74.833333,1.426441,-0.006192,0.162916
4,1aa498825382410b098937d65c4ec26d,usilxuppasemubllopkaafesmlibmsdf,8302,0,1998,f,181.21,33.12,33.12,1,...,0.000000,0.000000,0.000010,4.240524e-06,0.000000e+00,1,60.900000,2.887979,-0.008087,-0.000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14484,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,t,0.00,27.88,27.88,2,...,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0,48.166667,0.000000,-0.008653,0.177779
14485,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,f,15.94,0.00,0.00,1,...,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1,48.700000,0.300706,-0.007395,0.236694
14486,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,f,18.05,39.84,39.84,1,...,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1,48.666667,1.164859,-0.006192,0.162916
14487,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,f,0.00,13.08,13.08,1,...,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0,48.700000,0.000000,-0.003767,0.177779
14488,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,f,0.00,11.84,11.84,1,...,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0,85.200000,0.000000,-0.004628,-0.000001

In [137]:
df.drop(columns=['id', 'channel_sales'], inplace=True)

In [138]:
# Correct the values in has_gas column
df[df['has_gas'] == 'f'] = 1
df[df['has_gas'] == 't'] = 0
df['has_gas']

0        1
1        1
2        1
3        1
4        1
        ..
14484    0
14485    1
14486    1
14487    1
14488    1
Name: has_gas, Length: 14489, dtype: object